{{- $bl := empty .Values.influxURL }}
{{- if not $bl }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "kapacitor.fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    app: {{ template "kapacitor.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "kapacitor.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "kapacitor.fullname" . }}
    spec:
      initContainers:
    {{- if .Values.customInitContainers }}
{{ tpl .Values.customInitContainers . | indent 6 }}
    {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        {{- if .Values.env }}
{{- tpl (toYaml .Values.env) $ | nindent 8 }}
        {{- end }}
        - name: KAPACITOR_HOSTNAME
          value: {{ template "kapacitor.fullname" . }}.{{ .Release.Namespace }}
        - name: KAPACITOR_INFLUXDB_0_URLS_0
          value: {{ tpl .Values.influxURL . }}
        {{- if .Values.existingSecret }}
        - name: KAPACITOR_INFLUXDB_0_USERNAME
          valueFrom:
            secretKeyRef:
              key: influxdb-user
              name: {{ .Values.existingSecret }}
        - name: KAPACITOR_INFLUXDB_0_PASSWORD
          valueFrom:
            secretKeyRef:
              key: influxdb-password
              name: {{ .Values.existingSecret }}
        {{- end }}
        ports:
        - containerPort: 9092
        volumeMounts:
        {{- if .Values.existingConfigSecret }}
        - name: kapacitor-config
          mountPath: "/etc/kapacitor/kapacitor.conf"
          subPath: "kapacitor.conf"
        {{- end }}
        - name: data
          mountPath: /var/lib/kapacitor
        resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
        {{- if .Values.existingConfigSecret }}
        - name: kapacitor-config
          secret:
            secretName: {{ tpl .Values.existingConfigSecret . }}
        {{- end }}
        - name: data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "kapacitor.fullname" .) }}
        {{- else }}
          emptyDir: {}
        {{- end }}
{{- end }}
